#-----------------------------------------
# GitHub Actions for 'simple_fastapi' app
#-----------------------------------------

name: My-GitHub-Action-Basics
env:
  APPLICATION_NAME: "MyApp"
  PACKAGE_NAME    : "fastapi_ver_${{ github.sha }}"


on:
  push:
    branches: 
      - develop

jobs:
  build:
    name: Run Python tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: List project files and folders
      run : ls -la

    - name: Set up Python 3.10.4
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.4'
#
#    - name: Install Python dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#
#    - name: Test with pytest
#      run: |
#        pip install pytest pytest-cov
#        pytest tests/test_main.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
